# Workflow to run tests

name: Merge to Kotlin ToT tracking branch

on:
  push:
    branches: [ main ]

jobs:
  build-and-test-on-kotlin-tot:
    strategy:
      fail-fast: false

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: v1.5.20

    - name: merge commits from main to release branch
      run: |
        # merging main to release branch
        # git pull origin main
        git merge origin/main
        echo running tests
        git push origin
