# Workflow to run tests

name: CI

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    strategy:
      fail-fast: false

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: merge commits from main to release branch
      run: |
        # merging main to release branch
        BRANCH=v1.5.20
        git checkout -b $BRANCH origin/$BRANCH
        git pull origin main
        echo running tests
        git push origin $BRANCH
